#cloud-config
package_update: true
package_upgrade: true
users:
  - name: ryan
    groups: [ sudo ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh_import_id:
      - gh:greyhoundforty
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}